# Generated by Django 5.1.1 on 2024-10-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogmodel_user_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
